name: Resenia CI

on: 
  push:
   branches:
     - '*'
   

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Install jq
        if: github.ref == 'refs/heads/main'
        run: sudo apt-get install jq
      
      - name: Install Codacy
        if: github.ref == 'refs/heads/main'
        run: wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
      
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      
      - name: Run tests
        run: ./gradlew test -i
        
      - name: Update coverage report in Codacy
        if: success() && github.ref == 'refs/heads/main'
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Kotlin --force-language -r build/reports/jacoco/test/jacocoTestReport.xml
      
      - name: Deploy Heroku App
        if: success() && github.ref == 'refs/heads/main'
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_MAIL_ADDRESS}}       
      
      - name: Deploy Dev with Heroku
        if: success() && github.ref == 'refs/heads/development'
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_DEV_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_MAIL_ADDRESS}}    
